apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-100m
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /nfs_shared
    server: 192.168.1.10
